apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra-intelligence.fullname" . }}
  labels:
    {{- include "infra-intelligence.labels" . | nindent 4 }}
data:
  IIP_HTTP_HOST: {{ .Values.config.httpHost | quote }}
  IIP_HTTP_PORT: {{ .Values.config.httpPort | quote }}

