apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iip-database
  namespace: iip-system
  labels:
    app.kubernetes.io/part-of: infra-intelligence-platform
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: iip-production-secret-store
  target:
    name: iip-database
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: infra-intelligence-platform
  data:
    - secretKey: database-url
      remoteRef:
        key: infra-intelligence/production/database
        property: url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iip-database-ca
  namespace: iip-system
  labels:
    app.kubernetes.io/part-of: infra-intelligence-platform
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: iip-production-secret-store
  target:
    name: iip-database-ca
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: infra-intelligence-platform
  data:
    - secretKey: ca.crt
      remoteRef:
        key: infra-intelligence/production/database
        property: ca
